"""initial schema

Revision ID: 63903c166457
Revises: 
Create Date: 2026-04-11 13:00:47.064273+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63903c166457'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.String(length=255), nullable=False),
    sa.Column('job_url', sa.String(length=255), nullable=False),
    sa.Column('job_location', sa.String(length=255), nullable=False),
    sa.Column('job_salary', sa.String(length=255), nullable=True),
    sa.Column('job_company', sa.String(length=255), nullable=True),
    sa.Column('job_company_url', sa.String(length=255), nullable=True),
    sa.Column('application_detail_file_path', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bios',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resumes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('saved_preferences',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_preferences',
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('saved_preference_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['saved_preference_id'], ['saved_preferences.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'saved_preference_id')
    )
    op.create_table('job_hunts',
    sa.Column('platform', sa.String(length=255), nullable=False),
    sa.Column('bio_id', sa.String(length=36), nullable=True),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('categories', sa.Text(), nullable=False),
    sa.Column('locations', sa.Text(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('hiring_types', sa.Text(), nullable=True),
    sa.Column('industries', sa.Text(), nullable=True),
    sa.Column('work_style', sa.String(length=50), nullable=True),
    sa.Column('salary_min', sa.Text(), nullable=True),
    sa.Column('salary_max', sa.Text(), nullable=True),
    sa.Column('job_count', sa.Text(), nullable=False),
    sa.Column('extra_job_selection_intruction', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bio_id'], ['bios.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('bio_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('tools', sa.String(length=255), nullable=False),
    sa.Column('impact', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bio_id'], ['bios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experiences',
    sa.Column('bio_id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bio_id'], ['bios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experiences')
    op.drop_table('projects')
    op.drop_table('job_hunts')
    op.drop_table('category_preferences')
    op.drop_table('saved_preferences')
    op.drop_table('resumes')
    op.drop_table('categories')
    op.drop_table('bios')
    op.drop_table('applications')
    # ### end Alembic commands ###
